[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rare-quickprot"
version = "1.9.0" # Don't forget to match with version.py
authors = [
    { name="Anthony Aylward", email="anthony.aylward@protonmail.com" },
]
description = "homology-based method for predicting gene models across entire genomes"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "biopython",
    "TD2"
]

[project.urls]
"Homepage" = "https://github.com/anthony-aylward/quickprot"
"Documentation" = "https://github.com/anthony-aylward/quickprot"

[project.scripts]
quickprot = "quickprot:main"

[tool.setuptools]
package-dir = {quickprot="src/quickprot"}
script-files = [
    "src/quickprot/quickprot.py",
    "src/quickprot/add_type_gff3.py",
    "src/quickprot/extract_sequence_from_gff3.py",
    "src/quickprot/filter_repeatPeps_from_gff3.py",
    "src/quickprot/get_intron_from_gff3.py",
    "src/quickprot/get_longest_transcript_gff3.py",
    "src/quickprot/gtf_genome_to_cdna_fasta.py",
    "src/quickprot/rename_gff3.py",
    "src/quickprot/sm2rmForFasta.py",
    "src/quickprot/sort_gff3.py",
    "src/quickprot/split_and_filter_gene_model.py",
    "src/quickprot/stat_gff3.py",
    "src/quickprot/update_gff3_from_minibusco.py",
    "src/quickprot/gtf_to_alignment_gff3.pl",
    "src/quickprot/cdna_alignment_orf_to_genome_orf.pl",
    "src/quickprot/Fasta_reader.pm",
    "src/quickprot/Gene_obj.pm",
    "src/quickprot/GFF3_utils2.pm",
    "src/quickprot/Nuc_translator.pm",
    "src/quickprot/Longest_orf.pm"
]
